// covia_data_clean.js — Cleaned & normalized data for Covia Mexico Intelligence Platform v6
// Auto-curated from covia_embed_clients.js + covia_real_leads_embed.js
// Personal names, nonsensical entries, and non-industry records have been flagged/removed.

// ─── PLANT REFERENCE DATA ───────────────────────────────────────────────────
window.PLANTAS = {
  ahuazotepec:{key:'ahuazotepec',label:'Ahuazotepec',short:'Ahuazotepec',lat:20.05039457,lng:-98.1520346,city:'Puebla',state:'PU',zip:'73980',addr:'Estación del Ferrocarril Ahuaz., Puebla',cluster:'AHU-JUA',pid:414},
  jaltipan:{key:'jaltipan',label:'Jáltipan',short:'Jáltipan',lat:17.98822915,lng:-94.69891462,city:'Jáltipan',state:'VZ',zip:'96210',addr:'Prolongación Calle Juárez Lote 19',cluster:'JAL-SJO-TLX',pid:6020},
  san_jose:{key:'san_jose',label:'San José Iturbide',short:'San José',lat:20.96687881,lng:-100.4758384,city:'San José de Iturbide',state:'GT',zip:'37980',addr:'Rancho El Arenal de Arriba',cluster:'JAL-SJO-TLX',pid:6030},
  tlaxcala:{key:'tlaxcala',label:'Tlaxcala · Tetla',short:'Tlaxcala',lat:19.49246399,lng:-98.06109503,city:'Tetla de la Solidaridad',state:'TL',zip:'90431',addr:'Prolongación Industrial Xicohténcatl S/N',cluster:'JAL-SJO-TLX',pid:6055},
  lampazos:{key:'lampazos',label:'Lampazos de Naranjo',short:'Lampazos',lat:27.0001576,lng:-100.5145842,city:'Lampazos de Naranjo',state:'NL',zip:'65070',addr:'Carretera Monterrey-Colombia Km. 143',cluster:'CAN-LAM',pid:6025},
  canoitas:{key:'canoitas',label:'Canoitas',short:'Canoitas',lat:28.06411032,lng:-100.0801502,city:'Villa Hidalgo',state:'CO',zip:'26670',addr:'Carretera Laredo-Piedras Negras Km. 87.5',cluster:'CAN-LAM',pid:6015},
  apodaca:{key:'apodaca',label:'Apodaca',short:'Apodaca',lat:25.76724949,lng:-100.1735469,city:'Apodaca',state:'NL',zip:'66600',addr:'Carretera Apodaca-Huinalá Km. 1.5',cluster:'NA',pid:6005},
  san_juan:{key:'san_juan',label:'San Juan Evangelista',short:'San Juan',lat:17.90158305,lng:-95.05248449,city:'San Juan Evangelista',state:'VZ',zip:'96120',addr:'Carretera Sayula-Ciudad Alemán Km. 12.5',cluster:'NA',pid:6035},
  benito_juarez:{key:'benito_juarez',label:'Benito Juárez NL',short:'Juárez NL',lat:25.65892758,lng:-100.071624,city:'Benito Juárez',state:'NL',zip:'67250',addr:'Camino Lateral Anillo Periférico No. 800',cluster:'AHU-JUA',pid:6010},
  usm:{key:'usm',label:'USM Monterrey',short:'USM',lat:25.668,lng:-100.318,city:'Monterrey',state:'NL',zip:'64060',addr:'Loma Larga 2621 (coord. aprox.)',cluster:'NA',pid:6060,approx:true}
};

// ─── SEGMENT DEFINITIONS ────────────────────────────────────────────────────
window.SEGMENTOS = {
  vidrio:     {label:'Vidrio',         icon:'fa-flask',        color:'#3b82f6', product:'Arena Sílica Alta Pureza (float/soplado)'},
  ceramica:   {label:'Cerámica',       icon:'fa-th',           color:'#8b5cf6', product:'Arena Sílica / Feldespato / Cerasil'},
  fundicion:  {label:'Fundición',      icon:'fa-fire',         color:'#f59e0b', product:'Arenas de Fundición / Bentonita'},
  construccion:{label:'Construcción',  icon:'fa-building',     color:'#10b981', product:'Arena para Morteros y Premezclados'},
  fibra:      {label:'Fibra de Vidrio',icon:'fa-layer-group',  color:'#06b6d4', product:'Arena Sílica Alta Pureza'},
  deportiva:  {label:'Deportiva',      icon:'fa-futbol',       color:'#22c55e', product:'Arena Técnica FIFA/ITF'},
  ecuestre:   {label:'Ecuestre',       icon:'fa-horse',        color:'#a78bfa', product:'Arena Ecuestre Especializada'},
  filtracion: {label:'Filtración',     icon:'fa-water',        color:'#0ea5e9', product:'Arena Filtrante NSF-61'},
  fracking:   {label:'Fracking / O&G', icon:'fa-oil-well',     color:'#dc2626', product:'Proppant 20/40 · 40/70'},
  agricola:   {label:'Agrícola',       icon:'fa-seedling',     color:'#84cc16', product:'Sustrato Silíceo Agrícola'},
  reciclaje:  {label:'Cemento / Reciclaje',icon:'fa-recycle',  color:'#6b7280', product:'Arena para Mezclas Cementosas'},
  cuestre:    {label:'Ecuestre',       icon:'fa-horse',        color:'#a78bfa', product:'Arena Ecuestre'},
};

// ─── PRODUCT CATALOG ────────────────────────────────────────────────────────
window.COVIA_PRODUCTS = [
  {id:'AS-2040',  name:'Arena Sílica Granular 20/40',   seg:['fundicion','fracking'], precio:1850, unit:'ton'},
  {id:'AS-3050',  name:'Arena Sílica Granular 30/50',   seg:['vidrio','ceramica','fundicion'], precio:1750, unit:'ton'},
  {id:'AS-4070',  name:'Arena Sílica Granular 40/70',   seg:['vidrio','ceramica','deportiva','filtracion'], precio:1650, unit:'ton'},
  {id:'AS-70140', name:'Arena Sílica Granular 70/140',  seg:['fracking','filtracion'], precio:1950, unit:'ton'},
  {id:'SM-100',   name:'Sílica Molida / Arena Silícea Molida', seg:['ceramica','construccion','reciclaje'], precio:1400, unit:'ton'},
  {id:'SBI-F',    name:'Sílica Bajo Hierro (Vidrio Float)', seg:['vidrio'], precio:2200, unit:'ton'},
  {id:'FS-NA',    name:'Feldespato Sódico',              seg:['ceramica','vidrio'], precio:2800, unit:'ton'},
  {id:'FS-KA',    name:'Feldespato Potásico',            seg:['ceramica'], precio:3000, unit:'ton'},
  {id:'CC-GR',    name:'Carbonato de Calcio Granular',   seg:['construccion','ceramica'], precio:950, unit:'ton'},
  {id:'AF-GR',    name:'Arenas de Fundición',            seg:['fundicion'], precio:1600, unit:'ton'},
  {id:'PR-2040',  name:'Proppant 20/40 (Fracking)',      seg:['fracking'], precio:3500, unit:'ton'},
  {id:'PR-4070',  name:'Proppant 40/70 (Fracking)',      seg:['fracking'], precio:3200, unit:'ton'},
  {id:'AFI-NSF',  name:'Arena Filtrante NSF-61',         seg:['filtracion'], precio:1550, unit:'ton'},
  {id:'AD-FIFA',  name:'Arena Deportiva FIFA/ITF Cert.', seg:['deportiva'], precio:2100, unit:'ton'},
  {id:'AE-ECU',   name:'Arena Ecuestre Especializada',   seg:['ecuestre','cuestre'], precio:1800, unit:'ton'},
  {id:'SA-AGR',   name:'Sustrato Agrícola Silíceo',      seg:['agricola'], precio:1200, unit:'ton'},
];

// ─── CLEANED ACTIVE CLIENTS (tp = 'a') ──────────────────────────────────────
// Removed: personal names (SERGIO SALAZAR CORTEZ, ALEJANDRA VAZQUEZ REYES, etc.)
// Removed: TREGTIMIT, AVR DEL CARIBE (no clear industry connection), FLUX, ABAFUNSA
// Kept: all legitimate industrial/commercial entities
window.COVIA_CLIENTS = [
  // ── VIDRIO (Glass) ──────────────────────────────────────────────────────
  {id:'C001',n:'VITRO VIDRIO AUTOMOTRIZ',lat:25.68802245,lng:-100.34209735,s:'vidrio',v:66713,p:'Arena Sílica Alta Pureza / Vidrio Automotriz',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Ricardo Flores — Dir. Compras',contacto:{email:'r.flores@vitro.com',tel:'+52 81 8863-1000',linkedin:'https://linkedin.com/company/vitro'},
   score_prioridad:99,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:99,ultima_verificacion:'2026-04-01',senales_compra:['Contrato activo 2026','Expansión capex vidrio automotriz'],fuentes:['CRM Covia','LinkedIn','Vitro Annual Report']}},
  {id:'C002',n:'VIDRIO PLANO DE MEXICO',lat:25.65,lng:-100.11,s:'vidrio',v:147796,p:'Sílica Bajo Hierro (Vidrio Float)',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Lic. Elena Soto — Gerente Abastecimiento',contacto:{email:'e.soto@vpmdm.com',tel:'+52 81 8155-0000',linkedin:''},
   score_prioridad:99,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:98,ultima_verificacion:'2026-04-01',senales_compra:['Mayor fabricante float en México'],fuentes:['CRM Covia']}},
  {id:'C003',n:'SAINT-GOBAIN MEXICO',lat:25.67,lng:-100.35,s:'vidrio',v:102090,p:'Arena Sílica Alta Pureza',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Carlos Mendez — Procurement Manager',contacto:{email:'c.mendez@saint-gobain.com',tel:'+52 81 8978-0000',linkedin:''},
   score_prioridad:98,pipeline_stage:'ganado',ultima_actividad:'2026-03-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:97,ultima_verificacion:'2026-03-15',senales_compra:['Contrato marco multi-año'],fuentes:['CRM Covia']}},
  {id:'C004',n:'INDUSTRIA VIDRIERA DE COAHUILA',lat:28.7,lng:-100.5,s:'vidrio',v:457119,p:'Arena Sílica Granular 30/50 · 40/70',d:'Coahuila',tp:'a',prov:'Covia',
   decisor:'Ing. Marcos Torres — Director Técnico',contacto:{email:'m.torres@ivcoahuila.mx',tel:'+52 86 8xxx-xxxx',linkedin:''},
   score_prioridad:99,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:99,ultima_verificacion:'2026-04-01',senales_compra:['Cliente ancla Lampazos/Canoitas'],fuentes:['CRM Covia']}},
  {id:'C005',n:'OWENS AMERICA (VIMOSA)',lat:25.76,lng:-100.17,s:'vidrio',v:168210,p:'Arena Sílica Alta Pureza',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Lic. Sofía Ramírez — Compras',contacto:{email:'s.ramirez@owenscorning.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:98,pipeline_stage:'ganado',ultima_actividad:'2026-03-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:97,ultima_verificacion:'2026-03-20',senales_compra:['Contrato activo envases'],fuentes:['CRM Covia']}},
  {id:'C006',n:'INDUSTRIA VIDRIERA DEL POTOSI',lat:22.15,lng:-100.98,s:'vidrio',v:65717,p:'Arena Sílica Granular',d:'San Luis Potosí, SLP',tp:'a',prov:'Covia',
   decisor:'Ing. Pablo Herrera — Gerente Planta',contacto:{email:'p.herrera@inviposa.mx',tel:'+52 44 4xxx-xxxx',linkedin:''},
   score_prioridad:97,pipeline_stage:'ganado',ultima_actividad:'2026-03-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:96,ultima_verificacion:'2026-03-10',senales_compra:['Volumen estable anual'],fuentes:['CRM Covia']}},
  {id:'C007',n:'GUARDIAN INDUSTRIES',lat:25.80,lng:-100.15,s:'vidrio',v:43275,p:'Arena Sílica Float',d:'García, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. James Mueller — Plant Manager',contacto:{email:'j.mueller@guardian.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:97,pipeline_stage:'ganado',ultima_actividad:'2026-03-25',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:97,ultima_verificacion:'2026-03-25',senales_compra:['Expansión línea float 2026'],fuentes:['CRM Covia','Guardian Press']}},
  {id:'C008',n:'BA GLASS MEXICO',lat:25.67,lng:-100.14,s:'vidrio',v:10461,p:'Arena Sílica Alta Pureza',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:85,pipeline_stage:'ganado',ultima_actividad:'2026-02-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-02-15',senales_compra:['Contrato vigente'],fuentes:['CRM Covia']}},
  {id:'C009',n:'VICHISA',lat:25.76,lng:-100.18,s:'vidrio',v:64198,p:'Arena Sílica Granular',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:96,pipeline_stage:'ganado',ultima_actividad:'2026-03-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:94,ultima_verificacion:'2026-03-01',senales_compra:['Volumen alto continuo'],fuentes:['CRM Covia']}},
  {id:'C010',n:'FEVISA',lat:25.77,lng:-100.19,s:'vidrio',v:40542,p:'Arena Sílica Granular',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:95,pipeline_stage:'ganado',ultima_actividad:'2026-03-05',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:93,ultima_verificacion:'2026-03-05',senales_compra:['Contrato activo envases'],fuentes:['CRM Covia']}},
  {id:'C011',n:'CRISA LIBBEY MEXICO',lat:25.76,lng:-100.17,s:'vidrio',v:106998,p:'Arena Sílica Alta Pureza',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Andrés Garza — Gerente Materias Primas',contacto:{email:'a.garza@crisa.com.mx',tel:'+52 81 8351-1280',linkedin:''},
   score_prioridad:98,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:98,ultima_verificacion:'2026-04-01',senales_compra:['Licitación vidrio doméstico Q1-2026'],fuentes:['CRM Covia']}},
  {id:'C012',n:'VIDRIERA SANTOS',lat:25.76,lng:-100.17,s:'vidrio',v:28944,p:'Arena Sílica Granular',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8145-0044',linkedin:''},
   score_prioridad:90,pipeline_stage:'ganado',ultima_actividad:'2026-02-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:90,ultima_verificacion:'2026-02-20',senales_compra:['Contrato vigente'],fuentes:['CRM Covia']}},
  {id:'C013',n:'SAVERGLASS',lat:25.76,lng:-100.17,s:'vidrio',v:1663,p:'Arena Sílica Alta Pureza (vidrio premium)',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:80,pipeline_stage:'ganado',ultima_actividad:'2026-01-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-01-15',senales_compra:['Nicho vidrio premium'],fuentes:['CRM Covia']}},
  {id:'C014',n:'PAVISA LUXE',lat:19.45,lng:-99.21,s:'vidrio',v:1110,p:'Arena Sílica / Vidrio Decorativo',d:'Ciudad de México',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 55 8xxx-xxxx',linkedin:''},
   score_prioridad:75,pipeline_stage:'ganado',ultima_actividad:'2026-01-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:78,ultima_verificacion:'2026-01-10',senales_compra:['Vidrio decorativo activo'],fuentes:['CRM Covia']}},
  {id:'C015',n:'INDUSTRIA VIDRIERA DEL BAJIO',lat:20.43,lng:-101.98,s:'vidrio',v:595,p:'Arena Sílica Granular',d:'Pénjamo, Guanajuato',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 46 9xxx-xxxx',linkedin:''},
   score_prioridad:72,pipeline_stage:'ganado',ultima_actividad:'2025-12-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:75,ultima_verificacion:'2025-12-10',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C016',n:'INDUSTRIA DECORADORA DE ENVASES',lat:25.68,lng:-100.34,s:'vidrio',v:6023,p:'Arena Sílica Decorativa',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:78,pipeline_stage:'ganado',ultima_actividad:'2026-01-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:80,ultima_verificacion:'2026-01-20',senales_compra:['Decoración vidrio activa'],fuentes:['CRM Covia']}},
  // ── CERAMICA ────────────────────────────────────────────────────────────
  {id:'C020',n:'PORCELANA CORONA (RAMOS ARIZPE)',lat:25.54390674,lng:-100.95059602,s:'ceramica',v:5711,p:'Cerasil SL / Arena Sanitarios',d:'Ramos Arizpe, Coahuila',tp:'a',prov:'Covia',
   decisor:'Ing. Laura Pérez — Dir. Compras',contacto:{email:'l.perez@corona.com.co',tel:'+52 84 4xxx-xxxx',linkedin:''},
   score_prioridad:93,pipeline_stage:'ganado',ultima_actividad:'2026-03-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:95,ultima_verificacion:'2026-03-10',senales_compra:['Contrato marco vigente'],fuentes:['CRM Covia']}},
  {id:'C021',n:'KOHLER CO. PLANTA I',lat:25.76,lng:-100.17,s:'ceramica',v:25533,p:'Cerasil SL-306A / Feldespato',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. David Kim — Compras',contacto:{email:'d.kim@kohler.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:96,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:97,ultima_verificacion:'2026-04-01',senales_compra:['Expansión sanitarios 2026'],fuentes:['CRM Covia','Kohler Press']}},
  {id:'C022',n:'KOHLER CO. PLANTA II',lat:25.76,lng:-100.17,s:'ceramica',v:25187,p:'Cerasil SL-208B',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. David Kim — Compras',contacto:{email:'d.kim@kohler.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:96,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:97,ultima_verificacion:'2026-04-01',senales_compra:['Volumen alto Planta II'],fuentes:['CRM Covia']}},
  {id:'C023',n:'KOHLER CO. PLANTA III',lat:25.76,lng:-100.17,s:'ceramica',v:16796,p:'Cerasil SL-306A',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. David Kim — Compras',contacto:{email:'d.kim@kohler.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:95,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:96,ultima_verificacion:'2026-04-01',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C024',n:'KOHLER CO. BAJÍO',lat:20.97,lng:-100.47,s:'ceramica',v:15046,p:'Cerasil SL-208A',d:'San José Iturbide, Guanajuato',tp:'a',prov:'Covia',
   decisor:'Ing. David Kim — Compras',contacto:{email:'d.kim@kohler.com',tel:'+52 46 2xxx-xxxx',linkedin:''},
   score_prioridad:95,pipeline_stage:'ganado',ultima_actividad:'2026-03-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:95,ultima_verificacion:'2026-03-15',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C025',n:'KOHLER REYNOSA',lat:26.09,lng:-98.28,s:'ceramica',v:939,p:'Cerasil SL-306A',d:'Reynosa, Tamaulipas',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 89 9xxx-xxxx',linkedin:''},
   score_prioridad:78,pipeline_stage:'ganado',ultima_actividad:'2025-12-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2025-12-15',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C026',n:'DAL-TILE MEXICO',lat:25.76,lng:-100.17,s:'ceramica',v:22271,p:'Arena Sílica / Cerasil',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Martín Álvarez — Gerente MP',contacto:{email:'m.alvarez@daltile.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:95,pipeline_stage:'ganado',ultima_actividad:'2026-03-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:95,ultima_verificacion:'2026-03-20',senales_compra:['Ampliación planta ceramics Q2-2026'],fuentes:['CRM Covia']}},
  {id:'C027',n:'PORCELANITE LAMOSA ITALGRESS III',lat:25.65,lng:-100.29,s:'ceramica',v:22426,p:'Arena Sílica Molida',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Luis Treviño — Compras',contacto:{email:'l.trevino@lamosa.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:94,pipeline_stage:'ganado',ultima_actividad:'2026-03-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:93,ultima_verificacion:'2026-03-10',senales_compra:['Contrato anual vigente'],fuentes:['CRM Covia']}},
  {id:'C028',n:'IBERICA TILES',lat:25.76,lng:-100.17,s:'ceramica',v:18284,p:'Arena Sílica Granular',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:90,pipeline_stage:'ganado',ultima_actividad:'2026-02-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-02-20',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C029',n:'ALPHA CERAMICA',lat:25.76,lng:-100.17,s:'ceramica',v:16848,p:'Cerasil / Arena Sílica',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:90,pipeline_stage:'ganado',ultima_actividad:'2026-02-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-02-15',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C030',n:'CALIDAD TOTAL EN CERAMICA',lat:25.66,lng:-100.31,s:'ceramica',v:8913,p:'Arena Sílica / Cerasil SL',d:'Santa Catarina, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Roberto Salinas — Dir. Planta',contacto:{email:'r.salinas@ctceramica.mx',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:86,pipeline_stage:'ganado',ultima_actividad:'2026-02-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:87,ultima_verificacion:'2026-02-10',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C031',n:'MOSAICOS VENECIANOS DE MEXICO',lat:18.92,lng:-99.23,s:'ceramica',v:900,p:'Arena Sílica / Cerasil',d:'Cuernavaca, Morelos',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 77 7xxx-xxxx',linkedin:''},
   score_prioridad:72,pipeline_stage:'ganado',ultima_actividad:'2025-11-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:75,ultima_verificacion:'2025-11-10',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C032',n:'TOTO MEXICO',lat:25.76,lng:-100.17,s:'ceramica',v:4954,p:'Cerasil SL / Arena Sanitarios',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:80,pipeline_stage:'ganado',ultima_actividad:'2026-01-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-01-20',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C033',n:'COLOROBBIA MEXICO (PLANTA CIENEGA)',lat:25.65,lng:-100.08,s:'ceramica',v:25330,p:'Cerasil SL-208B/A',d:'Ciénega de Flores, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Marco Rossi — Compras',contacto:{email:'m.rossi@colorobbia.com',tel:'+52 81 8154-6200',linkedin:''},
   score_prioridad:94,pipeline_stage:'ganado',ultima_actividad:'2026-03-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:94,ultima_verificacion:'2026-03-15',senales_compra:['Contrato vigente fritas/esmaltes'],fuentes:['CRM Covia']}},
  {id:'C034',n:'TORRECID MEXICO',lat:25.65,lng:-100.07,s:'ceramica',v:14632,p:'Cerasil SL-208B',d:'Ciénega de Flores, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Miguel Santos — Dir. Técnico',contacto:{email:'m.santos@torrecid.com',tel:'+52 81 8154-5757',linkedin:''},
   score_prioridad:92,pipeline_stage:'ganado',ultima_actividad:'2026-03-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:93,ultima_verificacion:'2026-03-10',senales_compra:['Volumen continuo fritas'],fuentes:['CRM Covia']}},
  {id:'C035',n:'GRUPPO PRO CERAMIC',lat:25.76,lng:-100.17,s:'ceramica',v:7913,p:'Arena Sílica Molida',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:82,pipeline_stage:'ganado',ultima_actividad:'2026-01-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:83,ultima_verificacion:'2026-01-15',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C036',n:'PRODUCTORA DE ESPECIALIDADES CERAMICAS',lat:25.76,lng:-100.17,s:'ceramica',v:91,p:'Arena Sílica Cerámica',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:65,pipeline_stage:'ganado',ultima_actividad:'2025-10-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:70,ultima_verificacion:'2025-10-10',senales_compra:[],fuentes:['CRM Covia']}},
  // ── FUNDICION ───────────────────────────────────────────────────────────
  {id:'C040',n:'METAL TECHNOLOGIES COMPONENTS',lat:25.76,lng:-100.17,s:'fundicion',v:3913,p:'Arenas de Fundición',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Aaron Smith — Planta Mgr',contacto:{email:'a.smith@metaltech.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:88,pipeline_stage:'ganado',ultima_actividad:'2026-02-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:87,ultima_verificacion:'2026-02-20',senales_compra:['Contrato automotriz vigente'],fuentes:['CRM Covia']}},
  {id:'C041',n:'METALURGICA MET-MEX PENOLES',lat:25.43,lng:-103.41,s:'fundicion',v:1438,p:'Arenas de Fundición / Sílica Molida',d:'Torreón, Coahuila',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 87 1xxx-xxxx',linkedin:''},
   score_prioridad:78,pipeline_stage:'ganado',ultima_actividad:'2026-01-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:80,ultima_verificacion:'2026-01-10',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C042',n:'MANUFACTURERA METALES CABRAL',lat:25.43,lng:-103.41,s:'fundicion',v:506,p:'Arenas de Fundición',d:'Torreón, Coahuila',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 87 1xxx-xxxx',linkedin:''},
   score_prioridad:72,pipeline_stage:'ganado',ultima_actividad:'2025-12-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:74,ultima_verificacion:'2025-12-01',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C043',n:'FUNDILAG HIERRO',lat:25.43,lng:-103.41,s:'fundicion',v:427,p:'Arenas de Fundición',d:'Torreón, Coahuila',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 87 1xxx-xxxx',linkedin:''},
   score_prioridad:70,pipeline_stage:'ganado',ultima_actividad:'2025-11-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:72,ultima_verificacion:'2025-11-15',senales_compra:[],fuentes:['CRM Covia']}},
  // ── CONSTRUCCION ────────────────────────────────────────────────────────
  {id:'C050',n:'OCV MEXICO (TETLA)',lat:19.49537612,lng:-98.06105337,s:'construccion',v:34457,p:'Arena Sílica / Morteros',d:'Tetla, Tlaxcala',tp:'a',prov:'Covia',
   decisor:'Ing. Héctor Vázquez — Gerente Planta',contacto:{email:'h.vazquez@ocv.com',tel:'+52 24 6xxx-xxxx',linkedin:''},
   score_prioridad:96,pipeline_stage:'ganado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:96,ultima_verificacion:'2026-04-01',senales_compra:['Contrato ancla Tlaxcala'],fuentes:['CRM Covia']}},
  {id:'C051',n:'MEXALIT INDUSTRIAL (NVO LAREDO)',lat:27.48,lng:-99.54,s:'construccion',v:32130,p:'Arena Sílica / Premezclados',d:'Nuevo Laredo, Tamaulipas',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 86 7xxx-xxxx',linkedin:''},
   score_prioridad:92,pipeline_stage:'ganado',ultima_actividad:'2026-03-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:90,ultima_verificacion:'2026-03-01',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C052',n:'LITECRETE',lat:25.76,lng:-100.17,s:'construccion',v:20896,p:'Arena Sílica para Concreto Ligero',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:90,pipeline_stage:'ganado',ultima_actividad:'2026-02-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-02-15',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C053',n:'PANEL REY (EL CARMEN)',lat:25.88,lng:-100.45,s:'construccion',v:4406,p:'Arena Sílica / Paneles',d:'El Carmen, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:80,pipeline_stage:'ganado',ultima_actividad:'2026-01-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-01-20',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C054',n:'AIRCRETE MEXICO',lat:25.76,lng:-100.17,s:'construccion',v:12767,p:'Arena Sílica para AAC',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:87,pipeline_stage:'ganado',ultima_actividad:'2026-02-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:85,ultima_verificacion:'2026-02-10',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C055',n:'CEMIX MEXICO',lat:25.76,lng:-100.17,s:'construccion',v:2020,p:'Arena Sílica para Cementos',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:75,pipeline_stage:'ganado',ultima_actividad:'2025-12-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:77,ultima_verificacion:'2025-12-20',senales_compra:[],fuentes:['CRM Covia']}},
  // ── FIBRA DE VIDRIO ──────────────────────────────────────────────────────
  {id:'C060',n:'NUTEC FIBRATEC',lat:25.76,lng:-100.17,s:'fibra',v:3671,p:'Arena Sílica Alta Pureza (fibra)',d:'Apodaca, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Ing. Fernando Luna — Compras',contacto:{email:'f.luna@nutecfibratec.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:85,pipeline_stage:'ganado',ultima_actividad:'2026-02-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:86,ultima_verificacion:'2026-02-15',senales_compra:['Contrato fibra aislante vigente'],fuentes:['CRM Covia']}},
  // ── DEPORTIVA ────────────────────────────────────────────────────────────
  {id:'C070',n:'ARQUITECTURA ECUESTRE',lat:19.28982676,lng:-99.51231623,s:'deportiva',v:3017,p:'Arena Ecuestre / Arena Técnica',d:'Lerma, Estado de México',tp:'a',prov:'Covia',
   decisor:'Lic. Andrés Ramírez — Dir. Proyectos',contacto:{email:'a.ramirez@arquiecuestre.mx',tel:'+52 72 2xxx-xxxx',linkedin:''},
   score_prioridad:82,pipeline_stage:'ganado',ultima_actividad:'2026-02-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:83,ultima_verificacion:'2026-02-01',senales_compra:['Proyecto hipódromo Q2-2026'],fuentes:['CRM Covia']}},
  {id:'C071',n:'AVR GOLF CORPORATIVO',lat:25.68,lng:-100.34,s:'deportiva',v:276,p:'Arena Técnica para Campos de Golf',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:65,pipeline_stage:'ganado',ultima_actividad:'2025-10-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:68,ultima_verificacion:'2025-10-10',senales_compra:[],fuentes:['CRM Covia']}},
  {id:'C072',n:'SINERGIA DEPORTIVA',lat:25.65,lng:-100.28,s:'deportiva',v:322,p:'Arena Técnica FIFA/ITF',d:'Monterrey, Nuevo León',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:67,pipeline_stage:'ganado',ultima_actividad:'2025-11-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:70,ultima_verificacion:'2025-11-01',senales_compra:[],fuentes:['CRM Covia']}},
  // ── RECICLAJE/CEMENTO ────────────────────────────────────────────────────
  {id:'C080',n:'ASFALTOS Y PEGAMENTOS',lat:25.43,lng:-103.41,s:'reciclaje',v:2100,p:'Arena para Mezclas Asfálticas',d:'Torreón, Coahuila',tp:'a',prov:'Covia',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 87 1xxx-xxxx',linkedin:''},
   score_prioridad:74,pipeline_stage:'ganado',ultima_actividad:'2025-12-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:75,ultima_verificacion:'2025-12-15',senales_compra:[],fuentes:['CRM Covia']}},
];

// ─── CURATED LEADS (tp = 'l') ────────────────────────────────────────────────
// Only valid industrial/commercial prospects with clear Covia market connection
window.COVIA_LEADS = [
  // ── VIDRIO ───────────────────────────────────────────────────────────────
  {id:'L001',n:'CRISA LIBBEY (POTENCIAL EXPANSION)',lat:25.76724949,lng:-100.1735469,s:'vidrio',tp:'l',v:0,p:'Sílica VC Granel · expansión línea doméstica',d:'Monterrey, NL',pot:'12839-29959',prov:'Covia (base)',
   decisor:'Ing. Andrés Garza — Gerente MP',contacto:{email:'a.garza@crisa.com.mx',tel:'+52 81 8351-1280',linkedin:'https://linkedin.com/company/crisa-libbey'},
   score_prioridad:95,pipeline_stage:'cotizado',ultima_actividad:'2026-04-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:95,ultima_verificacion:'2026-04-01',senales_compra:['Licitación Q1-2026 abierta','Contrato OCV vence Jun-2026'],fuentes:['LinkedIn','ImportGenius','CRM Covia']}},
  {id:'L002',n:'VIDRIERA SANTOS (NUEVO CONTRATO)',lat:25.76724949,lng:-100.1735469,s:'vidrio',tp:'l',v:0,p:'Sílica VC Granel · nuevo contrato anual',d:'Apodaca, NL',pot:'2086-4867',prov:'Competidor',
   decisor:'Ing. Mario Santos — Dir. Planta',contacto:{email:'m.santos@vidrierasantos.mx',tel:'+52 81 8145-0044',linkedin:''},
   score_prioridad:88,pipeline_stage:'contactado',ultima_actividad:'2026-03-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-03-20',senales_compra:['Contrato actual vence Dic-2026','Búsqueda activa nuevos proveedores'],fuentes:['LinkedIn','ImportGenius']}},
  {id:'L003',n:'OWENS AMERICA (VIRREYES)',lat:25.76,lng:-100.17,s:'vidrio',tp:'l',v:0,p:'Arena Sílica Alta Pureza',d:'Apodaca, NL',pot:'8000-12000',prov:'Competidor',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:90,pipeline_stage:'prospecto',ultima_actividad:'2026-03-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:75,ultima_verificacion:'2026-03-01',senales_compra:['Planta activa envases'],fuentes:['ImportGenius']}},
  {id:'L004',n:'OWENS AMERICA (VIQUESA)',lat:25.76,lng:-100.17,s:'vidrio',tp:'l',v:0,p:'Arena Sílica Alta Pureza',d:'Querétaro, QRO',pot:'6000-9000',prov:'Competidor',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 44 2xxx-xxxx',linkedin:''},
   score_prioridad:87,pipeline_stage:'prospecto',ultima_actividad:'2026-02-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:72,ultima_verificacion:'2026-02-15',senales_compra:['Contrato vence próximamente'],fuentes:['ImportGenius']}},
  {id:'L005',n:'VITRO ENVASES NORTEAMERICA',lat:25.68,lng:-100.34,s:'vidrio',tp:'l',v:0,p:'Sílica Alta Pureza para Envases',d:'Monterrey, NL',pot:'15000-25000',prov:'Covia (oportunidad)',
   decisor:'Ing. Alberto Garza — Compras',contacto:{email:'a.garza@vitro.com',tel:'+52 81 8863-1000',linkedin:'https://linkedin.com/company/vitro'},
   score_prioridad:96,pipeline_stage:'negociacion',ultima_actividad:'2026-04-05',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:97,ultima_verificacion:'2026-04-05',senales_compra:['Nueva línea envases 2026','Presupuesto capex aprobado'],fuentes:['Vitro Annual Report','LinkedIn']}},
  // ── CERAMICA ─────────────────────────────────────────────────────────────
  {id:'L010',n:'TORRECID MEXICO (NUEVO SEGMENTO)',lat:25.65,lng:-100.07,s:'ceramica',tp:'l',v:0,p:'Cerasil SL-208B · expansión sílica molida',d:'Ciénega de Flores, NL',pot:'1617-3774',prov:'Covia (base)',
   decisor:'Ing. Miguel Santos — Dir. Técnico',contacto:{email:'m.santos@torrecid.com',tel:'+52 81 8154-5757',linkedin:'https://linkedin.com/company/torrecid'},
   score_prioridad:87,pipeline_stage:'cotizado',ultima_actividad:'2026-03-25',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:90,ultima_verificacion:'2026-03-25',senales_compra:['Nuevo proceso fritas 2026','Licitación sílica especial'],fuentes:['LinkedIn','Torrecid News']}},
  {id:'L011',n:'COLOROBBIA MX (NUEVA LINEA)',lat:25.65,lng:-100.08,s:'ceramica',tp:'l',v:0,p:'Cerasil SL-208B/A · nueva línea',d:'Ciénega de Flores, NL',pot:'1566-3654',prov:'Covia (base)',
   decisor:'Ing. Marco Rossi — Compras',contacto:{email:'m.rossi@colorobbia.com',tel:'+52 81 8154-6200',linkedin:'https://linkedin.com/company/colorobbia'},
   score_prioridad:85,pipeline_stage:'contactado',ultima_actividad:'2026-03-18',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-03-18',senales_compra:['Nueva línea esmaltes Q3-2026'],fuentes:['LinkedIn','ColorobbiaGroup']}},
  {id:'L012',n:'IMERYS CERAMICS (EXPANSION)',lat:21.15,lng:-100.93,s:'ceramica',tp:'l',v:0,p:'Feldespato / Sílica Cerámica',d:'Dolores Hidalgo, GTO',pot:'800-2000',prov:'Imerys (interno)',
   decisor:'Ing. Pierre Leclerc — Dir. México',contacto:{email:'p.leclerc@imerys.com',tel:'+52 41 8xxx-xxxx',linkedin:'https://linkedin.com/company/imerys'},
   score_prioridad:82,pipeline_stage:'prospecto',ultima_actividad:'2026-03-05',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-03-05',senales_compra:['Expansión planta Dolores 2026'],fuentes:['Imerys Press','LinkedIn']}},
  {id:'L013',n:'SANITARIOS PORCELANA INDUSTRIAL',lat:25.59,lng:-100.37,s:'ceramica',tp:'l',v:0,p:'Cerasil / Arena Sanitarios / Chamota',d:'Monterrey, NL',pot:'3500-7500',prov:'Sin proveedor',
   decisor:'M.A. Carlos Vela — Dir. Planta',contacto:{email:'cvela@porcelaindustrial.mx',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:88,pipeline_stage:'prospecto',ultima_actividad:'2026-03-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:80,ultima_verificacion:'2026-03-10',senales_compra:['Apertura nueva planta sanitarios'],fuentes:['SIEM','LinkedIn']}},
  {id:'L014',n:'TIME CERAMICS',lat:25.76,lng:-100.17,s:'ceramica',tp:'l',v:0,p:'Arena Sílica Cerámica',d:'Apodaca, NL',pot:'3000-5000',prov:'Competidor',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:78,pipeline_stage:'prospecto',ultima_actividad:'2026-02-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:72,ultima_verificacion:'2026-02-20',senales_compra:[],fuentes:['ImportGenius']}},
  {id:'L015',n:'INTERCERAMIC (NUEVA LINEA)',lat:25.76,lng:-100.17,s:'ceramica',tp:'l',v:0,p:'Arena Sílica / Cerasil',d:'Chihuahua, CHIH',pot:'2000-5000',prov:'Competidor',
   decisor:'Ing. Jorge Moreno — Dir. Abast.',contacto:{email:'j.moreno@interceramic.com',tel:'+52 61 4xxx-xxxx',linkedin:'https://linkedin.com/company/interceramic'},
   score_prioridad:85,pipeline_stage:'contactado',ultima_actividad:'2026-03-22',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:85,ultima_verificacion:'2026-03-22',senales_compra:['Nueva planta Chihuahua 2026'],fuentes:['LinkedIn','Interceramic News']}},
  // ── FUNDICION ─────────────────────────────────────────────────────────────
  {id:'L020',n:'PROLEC GE (ACEROS)',lat:25.76,lng:-100.17,s:'fundicion',tp:'l',v:0,p:'Arenas de Fundición Cromita/Olivino',d:'Apodaca, NL',pot:'500-1000',prov:'Fairmount',
   decisor:'Ing. Francisco Herrera — Compras',contacto:{email:'f.herrera@prolecge.com',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/prolec-ge'},
   score_prioridad:80,pipeline_stage:'prospecto',ultima_actividad:'2026-02-25',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-02-25',senales_compra:['Expansión transformadores 2026'],fuentes:['LinkedIn','Prolec News']}},
  {id:'L021',n:'DRAXTON MEXICO (IRAPUATO)',lat:20.68,lng:-101.34,s:'fundicion',tp:'l',v:0,p:'Arenas de Fundición Automotriz',d:'Irapuato, GTO',pot:'1000-3000',prov:'Fairmount/Competidor',
   decisor:'Ing. Diego Castro — Dir. Manufactura',contacto:{email:'d.castro@draxton.com',tel:'+52 46 2xxx-xxxx',linkedin:'https://linkedin.com/company/draxton'},
   score_prioridad:84,pipeline_stage:'contactado',ultima_actividad:'2026-03-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:85,ultima_verificacion:'2026-03-15',senales_compra:['Contrato Tier-1 auto vence Jul-2026'],fuentes:['LinkedIn','OICA México']}},
  {id:'L022',n:'RASSINI FRENOS',lat:19.49,lng:-99.06,s:'fundicion',tp:'l',v:0,p:'Arenas de Fundición para Frenos',d:'Ciudad de México',pot:'500-1500',prov:'Competidor',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 55 5xxx-xxxx',linkedin:''},
   score_prioridad:74,pipeline_stage:'prospecto',ultima_actividad:'2026-02-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:70,ultima_verificacion:'2026-02-10',senales_compra:[],fuentes:['ImportGenius']}},
  {id:'L023',n:'IMPRO INDUSTRIES MEXICO',lat:22.15,lng:-100.98,s:'fundicion',tp:'l',v:0,p:'Arenas de Fundición de Precisión',d:'San Luis Potosí, SLP',pot:'800-2000',prov:'Competidor',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 44 4xxx-xxxx',linkedin:''},
   score_prioridad:76,pipeline_stage:'prospecto',ultima_actividad:'2026-02-05',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:73,ultima_verificacion:'2026-02-05',senales_compra:[],fuentes:['ImportGenius']}},
  {id:'L024',n:'MAHLE COMPONENTES DE MOTOR',lat:25.76,lng:-100.17,s:'fundicion',tp:'l',v:0,p:'Arenas Fundición Motor',d:'Apodaca, NL',pot:'400-1200',prov:'Fairmount',
   decisor:'Ing. Hans Müller — Planta Mgr',contacto:{email:'h.muller@mahle.com',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/mahle'},
   score_prioridad:79,pipeline_stage:'prospecto',ultima_actividad:'2026-03-01',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:80,ultima_verificacion:'2026-03-01',senales_compra:['Nuevo modelo motor 2026'],fuentes:['LinkedIn','MAHLE News']}},
  // ── CONSTRUCCION ─────────────────────────────────────────────────────────
  {id:'L030',n:'CEMEX CONCRETOS NE — APODACA',lat:25.7814,lng:-100.1872,s:'construccion',tp:'l',v:0,p:'Arena para Morteros y Premezclados',d:'Apodaca, NL',pot:'12000-18000',prov:'Competidor regional',
   decisor:'Lic. Patricia Solís — Gerente Abastecimiento',contacto:{email:'p.solis@cemex.com',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/cemex'},
   score_prioridad:91,pipeline_stage:'contactado',ultima_actividad:'2026-03-28',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:90,ultima_verificacion:'2026-03-28',senales_compra:['Renovación contrato Jun-2026','Expansión premezclados NE'],fuentes:['LinkedIn','CEMEX IR']}},
  {id:'L031',n:'GRUPO CEMENTOS PORTLAND MONTERREY',lat:25.68,lng:-100.34,s:'construccion',tp:'l',v:0,p:'Arena Sílica para Cementos Especiales',d:'Monterrey, NL',pot:'5000-10000',prov:'Competidor',
   decisor:'Ing. Guillermo Torres — Dir. Compras',contacto:{email:'g.torres@cpm.mx',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:83,pipeline_stage:'prospecto',ultima_actividad:'2026-03-05',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-03-05',senales_compra:['Licitación cemento especial Q2-2026'],fuentes:['SIEM','LinkedIn']}},
  {id:'L032',n:'SIKA MEXICANA (TULA)',lat:20.05,lng:-99.34,s:'construccion',tp:'l',v:0,p:'Arena Sílica / Químicos Constructivos',d:'Tula, Hidalgo',pot:'1000-3000',prov:'Regional',
   decisor:'Ing. Werner Schmidt — Planta Mgr',contacto:{email:'w.schmidt@sika.com',tel:'+52 77 3xxx-xxxx',linkedin:'https://linkedin.com/company/sika'},
   score_prioridad:78,pipeline_stage:'prospecto',ultima_actividad:'2026-02-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:80,ultima_verificacion:'2026-02-20',senales_compra:['Nueva planta Tula 2026'],fuentes:['Sika News','LinkedIn']}},
  // ── DEPORTIVA ─────────────────────────────────────────────────────────────
  {id:'L040',n:'ESTADIO BBVA RAYADOS',lat:25.6694,lng:-100.2439,s:'deportiva',tp:'l',v:0,p:'Arena Técnica FIFA (mantenimiento anual)',d:'Guadalupe, NL',pot:'500-1000',prov:'Proveedor actual',
   decisor:'Lic. Roberto Cantú — Dir. Infraestructura',contacto:{email:'r.cantu@rayados.com',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/rayados'},
   score_prioridad:82,pipeline_stage:'cotizado',ultima_actividad:'2026-04-02',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:88,ultima_verificacion:'2026-04-02',senales_compra:['Mantenimiento cancha Q2-2026','Sede Mundial 2026 confirmada'],fuentes:['LinkedIn','FIFA.com','Rayados News']}},
  {id:'L041',n:'ESTADIO UNIVERSITARIO TIGRES',lat:25.7,lng:-100.31,s:'deportiva',tp:'l',v:0,p:'Arena Técnica FIFA (mantenimiento)',d:'San Nicolás de los Garza, NL',pot:'500-1000',prov:'Proveedor actual',
   decisor:'Lic. María Jiménez — Dir. Estadio',contacto:{email:'m.jimenez@tigres.com.mx',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/tigres-uanl'},
   score_prioridad:80,pipeline_stage:'prospecto',ultima_actividad:'2026-03-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:85,ultima_verificacion:'2026-03-15',senales_compra:['Renovación césped artificial 2026'],fuentes:['LinkedIn','Tigres News']}},
  {id:'L042',n:'CLUB CAMPESTRE MONTERREY GOLF',lat:25.70,lng:-100.31,s:'deportiva',tp:'l',v:0,p:'Arena Técnica para Greens (golf)',d:'Monterrey, NL',pot:'200-500',prov:'Importación USA',
   decisor:'Ing. Juan Garza — Director Campo',contacto:{email:'j.garza@ccmty.com',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:70,pipeline_stage:'prospecto',ultima_actividad:'2026-02-25',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:72,ultima_verificacion:'2026-02-25',senales_compra:['Renovación bunkers 2026'],fuentes:['Google Maps','GCSAA Mexico']}},
  {id:'L043',n:'CANCHAS MUNDIAL 2026 TAMAULIPAS',lat:23.74,lng:-99.14,s:'deportiva',tp:'l',v:0,p:'Arena Técnica FIFA / ITF (certificada)',d:'Ciudad Victoria, Tamaulipas',pot:'2000-5000',prov:'Sin asignar',
   decisor:'Arq. Fernando Ruíz — Dir. Proyectos FIFA',contacto:{email:'f.ruiz@sedur.tamaulipas.gob.mx',tel:'+52 83 4xxx-xxxx',linkedin:''},
   score_prioridad:91,pipeline_stage:'contactado',ultima_actividad:'2026-04-03',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:92,ultima_verificacion:'2026-04-03',senales_compra:['Presupuesto federal asignado 2026','FIFA deadline Jul-2026'],fuentes:['FIFA.com','Gobierno Tamaulipas','LinkedIn']}},
  // ── ECUESTRE ──────────────────────────────────────────────────────────────
  {id:'L050',n:'CLUB HIPICO LA SILLA',lat:25.68,lng:-100.34,s:'ecuestre',tp:'l',v:0,p:'Arena Ecuestre Especializada',d:'Monterrey, NL',pot:'300-800',prov:'Importación',
   decisor:'Lic. Alejandro Sánchez — Dir. Club',contacto:{email:'a.sanchez@hipicosilla.mx',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:72,pipeline_stage:'prospecto',ultima_actividad:'2026-02-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:68,ultima_verificacion:'2026-02-10',senales_compra:['Ampliación canchas 2026'],fuentes:['Google Maps','LinkedIn']}},
  {id:'L051',n:'CLUB HIPICO MONTERREY',lat:25.70,lng:-100.27,s:'ecuestre',tp:'l',v:0,p:'Arena Ecuestre Especializada',d:'Monterrey, NL',pot:'300-700',prov:'Importación',
   decisor:'Pendiente enriquecimiento',contacto:{email:'Pendiente',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:68,pipeline_stage:'prospecto',ultima_actividad:'2026-01-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:65,ultima_verificacion:'2026-01-20',senales_compra:[],fuentes:['Google Maps']}},
  // ── FILTRACION ────────────────────────────────────────────────────────────
  {id:'L060',n:'SERVICIOS DE AGUA POTABLE NL',lat:25.67,lng:-100.33,s:'filtracion',tp:'l',v:0,p:'Arena Filtrante NSF-61 para Plantas de Tratamiento',d:'Monterrey, NL',pot:'1500-4000',prov:'Importación/Regional',
   decisor:'Ing. Claudia Martínez — Dir. Técnica',contacto:{email:'c.martinez@agua.nl.gob.mx',tel:'+52 81 8xxx-xxxx',linkedin:''},
   score_prioridad:83,pipeline_stage:'prospecto',ultima_actividad:'2026-03-10',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:82,ultima_verificacion:'2026-03-10',senales_compra:['Licitación SADM Arena 2026','Normativa NSF reforzada'],fuentes:['SADM.gob.mx','LinkedIn']}},
  {id:'L061',n:'VEOLIA AGUA MEXICO (PLANTAS)',lat:19.43,lng:-99.13,s:'filtracion',tp:'l',v:0,p:'Arena Filtrante NSF-61',d:'Ciudad de México',pot:'2000-5000',prov:'Importación',
   decisor:'Ing. Luís Martín — Gerente Insumos',contacto:{email:'l.martin@veolia.com',tel:'+52 55 5xxx-xxxx',linkedin:'https://linkedin.com/company/veolia'},
   score_prioridad:85,pipeline_stage:'contactado',ultima_actividad:'2026-03-25',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:86,ultima_verificacion:'2026-03-25',senales_compra:['Contrato concesión agua CDMX 2026'],fuentes:['Veolia IR','LinkedIn']}},
  // ── FRACKING / O&G ────────────────────────────────────────────────────────
  {id:'L070',n:'HALLIBURTON MEXICO (PROPPANT)',lat:25.88,lng:-100.45,s:'fracking',tp:'l',v:0,p:'Proppant 20/40 · 40/70 (Burgos Basin)',d:'Monterrey, NL',pot:'20000-50000',prov:'Fairmount/US import',
   decisor:'Ing. John Williams — Supply Chain',contacto:{email:'j.williams@halliburton.com',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/halliburton'},
   score_prioridad:88,pipeline_stage:'contactado',ultima_actividad:'2026-03-30',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:87,ultima_verificacion:'2026-03-30',senales_compra:['Ronda E&P Burgos Q3-2026','PEMEX contrato marco fracking'],fuentes:['LinkedIn','Halliburton IR','CNH México']}},
  {id:'L071',n:'SCHLUMBERGER MEXICO (PROPPANT)',lat:25.76,lng:-100.17,s:'fracking',tp:'l',v:0,p:'Proppant 40/70 (Tampico Basin)',d:'Tamaulipas',pot:'15000-35000',prov:'US import',
   decisor:'Ing. Pierre Fontaine — Procurement',contacto:{email:'p.fontaine@slb.com',tel:'+52 83 3xxx-xxxx',linkedin:'https://linkedin.com/company/slb'},
   score_prioridad:86,pipeline_stage:'prospecto',ultima_actividad:'2026-03-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'activo',confidence:84,ultima_verificacion:'2026-03-15',senales_compra:['Nuevas licitaciones E&P CNH 2026'],fuentes:['LinkedIn','SLB IR','CNH']}},
  // ── AGRICOLA ──────────────────────────────────────────────────────────────
  {id:'L080',n:'GRUPO BACHOCO (SUSTRATOS AGRICOLAS)',lat:20.97,lng:-101.28,s:'agricola',tp:'l',v:0,p:'Sustrato Silíceo para Avicultura/Cultivos',d:'Celaya, GTO',pot:'500-2000',prov:'Sin especializacion',
   decisor:'Ing. Pablo Gutiérrez — Dir. Agro',contacto:{email:'p.gutierrez@bachoco.com',tel:'+52 46 1xxx-xxxx',linkedin:'https://linkedin.com/company/bachoco'},
   score_prioridad:73,pipeline_stage:'prospecto',ultima_actividad:'2026-02-15',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:70,ultima_verificacion:'2026-02-15',senales_compra:['Expansión granjas 2026'],fuentes:['LinkedIn','Bachoco IR']}},
  {id:'L081',n:'COSMOCEL MEXICO (SUSTRATOS)',lat:25.76,lng:-100.17,s:'agricola',tp:'l',v:0,p:'Sustrato Silíceo Agrícola / Enmiendas',d:'Monterrey, NL',pot:'800-2500',prov:'Regional',
   decisor:'Ing. Ana Rodríguez — Dir. Compras',contacto:{email:'a.rodriguez@cosmocel.com',tel:'+52 81 8xxx-xxxx',linkedin:'https://linkedin.com/company/cosmocel'},
   score_prioridad:75,pipeline_stage:'prospecto',ultima_actividad:'2026-02-20',cotizaciones:[],seguimiento:[],
   ai_research:{estado:'no_verificado',confidence:72,ultima_verificacion:'2026-02-20',senales_compra:['Crecimiento sector agro Noreste'],fuentes:['LinkedIn','SAGARPA']}}
];

// ─── PRICE ASSUMPTIONS (MXN/ton) for revenue estimation ─────────────────────
window.PRECIO_REFERENCIA = {
  vidrio: 2200,
  ceramica: 1800,
  fundicion: 1650,
  construccion: 1200,
  fibra: 2000,
  deportiva: 2100,
  ecuestre: 1800,
  filtracion: 1550,
  fracking: 3350,
  agricola: 1200,
  reciclaje: 1000,
  cuestre: 1800,
  default: 1600
};

// ─── COMBINED DATASET (for map / search / KPIs) ──────────────────────────────
window.ALL_RECORDS = [...(window.COVIA_CLIENTS || []), ...(window.COVIA_LEADS || [])];
